# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f0bf03c00bcf2e2d2ef1495c06f611f8b2bf0ff1c09e2a07db052a6024419b57ea0aa60674a3b2c0a457ba8d61be136fbacd1d5cad16ae6c8359a4fa679f2fd5

test:
  secret_key_base: cd1c72eb035943a62cc8d76db509f90b76ec7de236cb0473731f90b3dc1d819f4d761d239913f2a677965ce430d6c3a47f4a9488a75ba0c891295ff6f0017057

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
